### ISSUE TITLE
Table with triggers error out on UPDATE

### ISSUE THREAD

**Issue by yorek** [Azure/data-api-builder#452] opened 2022-05-27 00:51 UTC
If a table has a trigger, the following error is generated:

```
Route matched with {action = "Post", controller = "GraphQL"}. Executing controller action with signature System.Threading.Tasks.Task`1[System.Text.Json.JsonElement] PostAsync() on controller Azure.DataGateway.Service.Controllers.GraphQLController (Azure.DataGateway.Service).
UPDATE [s001].[todos] SET [s001].[todos].[title] = @param1 OUTPUT Inserted.[id] WHERE [s001].[todos].[id] = @param0;
Microsoft.Data.SqlClient.SqlException (0x80131904): The target table 's001.todos' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause.
```

**Comment by ayush3797** [comment] 2023-07-18 08:54
I spent some time doing exploration on this issue and will be documenting my findings here.

1. We can use `OUTPUT` clause if a trigger is not defined.

**Demonstration using T-SQL:**

```tsql
-- Creating a table TWOT (table without trigger) and fetching data using OUTPUT clause 
-- works fine since no trigger is created (and enabled) for the table.
DROP TABLE IF EXISTS TWOT;
create Table TWOT(
id int PRIMARY KEY,
title varchar(50)
);
INSERT INTO TWOT(id,title) values(1,'book');
update TWOT set title='DAB' output inserted.id,inserted.title where id=1;
```

2. `OUTPUT` clause used on a table with trigger configured errors out - if not used with `INTO` clause.

**Demonstration using T-SQL:**
```tsql
DROP TABLE IF EXISTS TWT;
create Table TWT(
id int PRIMARY KEY,
title varchar(50)
);
INSERT INTO TWT(id,title) values(1,'book');
CREATE OR ALTER TRIGGER TWT_AFTER_TRIGGER ON TWT AFTER UPDATE AS
BEGIN
    UPDATE TWT
    SET title = 'triggerExec'
    FROM TWT
    INNER JOIN deleted ON TWT.id = deleted.id;
END;
update TWT set title='DAB' output inserted.id,inserted.title where id=1;
```
3. `OUTPUT` clause used on a table with trigger configured works fine if used with `INTO` clause.

**Demonstration using T-SQL:**
```tsql
DROP TABLE IF EXISTS TWT;
create Table TWT(
id int PRIMARY KEY,
title varchar(50)
);
INSERT INTO TWT(id,title) values(1,'book');
CREATE OR ALTER TRIGGER TWT_AFTER_TRIGGER ON TWT AFTER UPDATE AS
BEGIN
    UPDATE TWT
    SET title = 'triggerExec'
    FROM TWT
    INNER JOIN deleted ON TWT.id = deleted.id;
END;
-- Create a temporary table to store the updated data
DECLARE @UpdatedData TABLE(
    id INT,
    title VARCHAR(50)
);

-- Perform the update and insert the updated data into the temporary table
UPDATE TWT
SET title = 'DAB'
OUTPUT inserted.id, inserted.title INTO @UpdatedData
where id = 1;

-- Retrieve the inserted data using PK from temp table
SELECT TWT.*
FROM TWT
INNER JOIN (
    SELECT id FROM @UpdatedData
) AS UD ON TWT.id = UD.id;
```
4. But approach#3 does not work when there is a column with timestamp data type.

**Demonstration using T-SQL:**
```tsql
DROP TABLE IF EXISTS TWT;
create Table TWT(
id int PRIMARY KEY,
title varchar(50),
RV timestamp
);
INSERT INTO TWT(id,title) values(1,'book');
CREATE OR ALTER TRIGGER TWT_AFTER_TRIGGER ON TWT AFTER UPDATE AS
BEGIN
    UPDATE TWT
    SET title = 'triggerExec'
    FROM TWT
    INNER JOIN deleted ON TWT.id = deleted.id;
END;
-- Create a temporary table to store the updated data
DECLARE @UpdatedData TABLE(
    id INT,
    title VARCHAR(50),
	RV timestamp
);

-- Perform the update and insert the updated data into the temporary table
UPDATE TWT
SET title = 'DAB'
OUTPUT inserted.id, inserted.title,inserted.RV INTO @UpdatedData
where id = 1;
```

**Comment by ayush3797** [comment] 2023-07-18 08:55
**Inferences:**
1. We can use `OUTPUT` clause if a _trigger is not defined_.
2. We can only use `OUTPUT` clause if a trigger is defined it we _couple the OUTPUT clause with INTO clause_.
3. `OUTPUT` clause returns the _data as it is before the trigger(if any) executes_.
4. It might have occurred that we can use `INTO` CLAUSE to insert all the data into a temp table and return it. But it has a problem when there is a column with `timestamp` datatype in the table as we _cannot insert a value for timestamp column even in a temporary table._

**Comment by ayush3797** [comment] 2023-07-18 09:02
**Suggested solution:**
We can use `OUTPUT` clause coupled with `INTO` clause to store the values for the primary keys in a temporary table. And then do a subsequent select query on the table to get the data using those primary keys (have demonstrated this in #3). We can chose to go with this approach only if we determine that there are any triggers enabled on the table.

Two assumptions which I am taking that I want to put ahead (btw, I don't think those are valid use cases) are:

1. **What if primary key column has a datatype of timestamp?** Well, `rowversion`/`timestamp` is intended for versioning and tracking changes within a table, rather than serving as a primary key. _Moroever they have only binary(8) storage_. Also, by design, primary key values should not be modified after they have been assigned to a record. So having a PK with timestamp datatype does not seem to be a valid use case to me.

2. **What if the trigger updates the values of the primary keys** and the subsequent select we are going to perform returns no data because the values of the PK has been changed in the table? While it is technically possible to update the values of primary keys using triggers, it is generally not recommended and can lead to undesirable consequences.
Changing the value of a primary key can result in data integrity issues, as it may cause conflicts or break referential integrity constraints if other tables are referencing the primary key. It can also lead to confusion and difficulty in identifying records uniquely.

**Comment by ayush3797** [comment] 2023-07-18 10:12
What would handling of different kind of mutations look like when a trigger is enabled on it?

1. **DELETE:** We don't need to return any data for deletions, so nothing will change for deletions.

2. **UPDATE:** For updates, we will cease to use the output clause. Instead, we will do a subsequent select query on the table to get the data. Since PK would already be provided to us we can easily do a select query. Not to mention, we can do this only when we determine that there is indeed a trigger enabled on the table. If not, we can continue with the same query that we generate in present day.

3. **INSERT:** When it comes to insertions, we can perform insertions on two kind of tables:
  1. Tables with non-auto generated primary keys: When we have tables with non-autogen PK, we can do exactly what we would do for update operations as explained before.
  2. Tables with auto-gen primary keys: Whenever one or more column from PK is autogenerated for a table, we consider the PK as autogenerated. For tables with autogen PK, we would not be aware of the PK beforehand and so we cannot directly perform the subsequent select query. To get the primary key, we can use approach#3 as I explained in the comment: https://github.com/Azure/data-api-builder/issues/452#issuecomment-1639811191. Let us discuss more about this approach and the considerations:

**Delving deeper into Approach#3:**
We can use `OUTPUT` clause coupled with `INTO` clause to store the values for the primary keys in a temporary table. And then do a subsequent select query on the table to get the data using those primary keys (have demonstrated this in #3). We can chose to go with this approach only if we determine that there are any triggers enabled on the table.

Two assumptions which I am taking that I want to put ahead (btw, I don't think those are valid use cases) are:

1. **What if primary key column has a datatype of timestamp?** Well, `rowversion`/`timestamp` is intended for versioning and tracking changes within a table, rather than serving as a primary key. Also, by design, primary key values should not be modified after they have been assigned to a record. So having a PK with timestamp datatype does not seem to be a valid use case to me.

2. **What if the trigger updates the values of the primary keys** and the subsequent select we are going to perform returns no data because the values of the PK has been changed in the table? While it is technically possible to update the values of primary keys using triggers, it is generally not recommended and can lead to undesirable consequences.
Changing the value of a primary key can result in data integrity issues, as it may cause conflicts or break referential integrity constraints if other tables are referencing the primary key. It can also lead to confusion and difficulty in identifying records uniquely.

**Closed** 2023-09-14 20:08 UTC
Labels: bug, mssql, improvement
