### ISSUE TITLE
[Bug]: Error 500 trying to insert new record

### ISSUE THREAD

**Issue by simonetarantino97** [Azure/data-api-builder#1537] opened 2023-06-19 12:19 UTC
### What happened?

when I try to do a post/patch operation to insert a new record, I get this error message:

error": {
        "code": "DatabaseOperationFailed",
        "message": "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE @ROWCOUNT > 0' at line 1",
        "status": 500
    }

### Version

0,7,6+61de247acf65280d93783072226f695536591ffb

### What database are you using?

MySQL

### What hosting model are you using?

Static Web Apps (SWA)

### Which API approach are you accessing DAB through?

REST

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by severussundar** [comment] 2023-06-19 14:54
Thanks @simonetarantino97 very much for bringing this to our attention. We will investigate and get back.

**Comment by simonetarantino97** [comment] 2023-06-19 16:27
If you need more infos about it I can give you my dab-config.MySql.json. I want to inform you that I am using an amazon mysql server, I don't know if this could be the problem, if not I hope it can help you

**Comment by severussundar** [comment] 2023-06-21 13:22
Hey @simonetarantino97, I was able to reproduce this with MySQL version 5.7

Using MySQL version 8, POST and PATCH requests work fine. Please consider using MySQL version 8.

**Comment by simonetarantino97** [comment] 2023-06-21 13:36
Thank you!
Yes, I confirm that I'm using MySql version 5.7 (to be more precise 5.7.12). I will definitely consider using version 8 for my next projects.

Thanks again, I really appreciated it

**Comment by simonetarantino97** [comment] 2023-06-22 15:33
Forgive me for posting here, is there a way to implement/personalize the CRUDs with some business oriented code written by me?

I usually write REST API in C#, it will be fantastic if I can make little modifications to the CRUDs starting on what DAB generate.

Thank you in advance!

**Comment by severussundar** [comment] 2023-06-26 10:06
Hi @simonetarantino97, thank you for your question.

With REST APIs, we support query parameters such as `$select`, `$filter`, etc. which lets you customize the REST behavior to a certain extent. The [DAB REST docs](https://learn.microsoft.com/azure/data-api-builder/rest) explains this in  detail. 

With SQL Server (or) Azure SQL DBs, we support stored procedures through both REST and GraphQL, which also enables you to execute custom business logic. 

Please share more details about your use-case, if possible, to see if it can (and how) be achieved through Data API builder.

**Comment by simonetarantino97** [comment] 2023-06-28 14:30
Thank you for the reply!

Sorry for the late reply.. I would need, if possible, for example, to generate codes based on the data that is entered during the insert or update operations and then insert them in certain columns. How can I do? Is it possible?

Thank you in advance

**Comment by severussundar** [comment] 2023-06-30 10:58
Thank you for sharing more details.

Through the features available in DAB at the moment, this can be achieved in the following ways, 

-  Exposing the second entity through REST and making two API calls:  Since, the data that is passed to the first entity should be available at the client layer, the computation logic can be performed to determine the values to be inserted in the second entity and then a second REST API call to insert this computed data can be invoked.
-  Stored Procedures: Enclosing the insertion and computation logic in a stored procedure and passing the data to be inserted as params.


While these suggestions may/may not be ideal for your use-case, please feel free to share any concerns that you might have with these suggestions - it will help us to build new features/enhance existing ones.

**Comment by seantleonard** [comment] 2024-04-19 17:21
Closing because this issue looks to be caused by older MySql version `5.7` which dab does not officially support per https://learn.microsoft.com/azure/data-api-builder/reference-database-specific-features#database-version-support

**Closed by seantleonard** 2024-04-19 17:21 UTC
Labels: bug, wontfix
