### ISSUE TITLE
Identify and implement any missing SQL Types in test coverage.

### ISSUE THREAD

**Issue by aaronburtle** [Azure/data-api-builder#1534] opened 2023-06-13 21:37 UTC
We currently support a wide range of types, however there are potentially types that are supported by SQL that we still lack. This task is to identify those types and to add those types to tests. This will mean modifying the table used in testing with the supported types and expanding any tests that make use of that table to include all of the supported types now included after this change.

**Comment by Aniruddh25** [comment] 2023-07-07 20:30
Duplicate of #1533

**Closed by Aniruddh25** 2023-07-07 20:30 UTC
Labels: testing
