### ISSUE TITLE
[Bug]: Using the word Asset as a model returns an error in version 0.7.6

### ISSUE THREAD

**Issue by dgcaron** [Azure/data-api-builder#1538] opened 2023-06-20 08:49 UTC
### What happened?

i have the following gql schema:

```gql
type Asset @model {
  id: ID
  type: String
  name: String
  collection: String
  data: AssetData
  shares: [AssetShare]
  modifiedOn: String
}

type AssetData {
  contentType: String!
  host: String
  container: String!
  path: String
}

type AssetShare {
  id: String!
  target: String
  host: String
  container: String
  path: String
}
```

and this worked fine with versions prior to 0.7.6.  this version fails with the following response:

```json
{
  "errors": [
    {
      "message": "GraphQL type doesn't match any entity name or singular type in the runtime config.",
      "extensions": {
        "code": "BadRequest"
      }
    }
  ]
}
```

i have tried putting the plural and singular names in the configuration like this:

```json
"Asset": {
      "source": "models",
      "graphql": {
        "type": {
          "singular": "Asset",
          "plural": "Assets"
        }
      },
```

but it doesn't seem to solve it either.

### Version

0.7.6 (part of the swa cli)

### What database are you using?

CosmosDB NoSQL

### What hosting model are you using?

Local (including CLI)

### Which API approach are you accessing DAB through?

GraphQL

### Relevant log output

```Text
[dataApi] fail: Azure.DataApiBuilder.Service.Startup[0]
[dataApi]          at Azure.DataApiBuilder.Service.Services.MetadataProviders.CosmosSqlMetadataProvider.GetEntityName(String graphQLType) in /_/src/Service/Services/MetadataProviders/CosmosSqlMetadataProvider.cs:line 320
[dataApi]          at Azure.DataApiBuilder.Service.Models.GQLFilterParser.Parse(IMiddlewareContext ctx, IInputField filterArgumentSchema, List`1 fields, BaseQueryStructure queryStructure) in /_/src/Service/Models/GraphQLFilterParsers.cs:line 198
[dataApi]          at Azure.DataApiBuilder.Service.Models.GQLFilterParser.ParseAndOr(IMiddlewareContext ctx, IInputField argumentSchema, IInputField filterArgumentSchema, List`1 fields, BaseQueryStructure baseQuery, PredicateOperation op) in /_/src/Service/Models/GraphQLFilterParsers.cs:line 430
[dataApi]          at Azure.DataApiBuilder.Service.Models.GQLFilterParser.Parse(IMiddlewareContext ctx, IInputField filterArgumentSchema, List`1 fields, BaseQueryStructure queryStructure) in /_/src/Service/Models/GraphQLFilterParsers.cs:line 56
[dataApi]          at Azure.DataApiBuilder.Service.Resolvers.CosmosQueryStructure.Init(IDictionary`2 queryParams) in /_/src/Service/Resolvers/CosmosQueryStructure.cs:line 168
[dataApi]          at Azure.DataApiBuilder.Service.Resolvers.CosmosQueryEngine.ExecuteAsync(IMiddlewareContext context, IDictionary`2 parameters) in /_/src/Service/Resolvers/CosmosQueryEngine.cs:line 64
[dataApi]          at Azure.DataApiBuilder.Service.Services.ResolverMiddleware.InvokeAsync(IMiddlewareContext context) in /_/src/Service/Services/ResolverMiddleware.cs:line 95
[dataApi]          at HotChocolate.Utilities.MiddlewareCompiler`1.ExpressionHelper.AwaitTaskHelper(Task task)
[dataApi]          at HotChocolate.Execution.Processing.Tasks.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)
[dataApi]          at HotChocolate.Execution.Processing.Tasks.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dgcaron** [comment] 2023-06-20 09:07
please note that this error does not occur on the deployed version with the azure static webapps. promoting this version to production will break at least my environment.

**Comment by sajeetharan** [comment] 2023-06-20 15:21
@dgcaron  Are you getting this error when you try to start the engine?

**Comment by dgcaron** [comment] 2023-06-20 16:14
No, I get the error when invoke the endpoint to retrieve a list of assets. The exact same call works on v0.6.14

**Comment by sajeetharan** [comment] 2023-06-20 17:49
Is your config similar to this? 

```
{
  "$schema": "https://github.com/Azure/data-api-builder/releases/download/v0.7.6/dab.draft.schema.json",
  "data-source": {
    "database-type": "cosmosdb_nosql",
    "options": {
      "database": "PlaygroundDB",
      "schema": "schema.gql"
    },
    "connection-string": ""
  },
  "runtime": {
    "graphql": {
      "allow-introspection": true,
      "enabled": true,
      "path": "/graphql"
    },
    "host": {
      "mode": "development",
      "cors": {
        "origins": [],
        "allow-credentials": false
      },
      "authentication": {
        "provider": "StaticWebApps"
      }
    }
  },
  "entities": {
    "Asset": {
      "source": "Asset",
      "graphql": {
        "type": {
          "singular": "Asset",
          "plural": "Assets"
        }
      },
      "permissions": [
        {
          "actions": [
            "*"
          ],
          "role": "anonymous"
        }
      ]
    }
  }
}
```

Or can you share the whole config file?

**Comment by dgcaron** [comment] 2023-06-20 18:16
This looks pretty much like my setup at the moment with the exception of the authentication part. I'll try to make a minimal repro tomorrow.

**Comment by Aniruddh25** [comment] 2023-06-21 04:40
hi @dgcaron, are you using `filter` while retrieving the list of assets? 

Also, does your configuration contain the entities - `AssetData` and `AssetShare`?
If not, could you please try adding those to the config as well?

**Comment by dgcaron** [comment] 2023-06-22 06:58
[repro-bug.zip](https://github.com/Azure/data-api-builder/files/11829803/repro-bug.zip)

i am calling this with:

```gql
query GetAssets($domain: String) {
	assets(
		filter: {
			and: [
				{ type: { eq: "asset" } }
				{ collection: { eq: $domain } }
				{ data: { container: { neq: $domain } } }
			]
		}
	) {
		items {
			__typename
			id
			name
			data {
				host
				container
				path
			}
			shares {
				id
				host
				container
				path
			}
			modifiedOn
		}
	}
}
```
with the following variables
```json
{
	"domain": "relaties"
}
```

**Comment by sajeetharan** [comment] 2023-06-22 17:21
hi @dgcaron can you try with the below config as @Aniruddh25 suggested above?

```
{
  "$schema": "https://github.com/Azure/data-api-builder/releases/download/v0.7.6/dab.draft.schema.json",
  "data-source": {
    "database-type": "cosmosdb_nosql",
    "options": {
      "database": "PlaygroundDB",
      "schema": "schema.gql"
    },
    "connection-string": ""
  },
  "runtime": {
    "graphql": {
      "allow-introspection": true,
      "enabled": true,
      "path": "/graphql"
    },
    "host": {
      "mode": "development",
      "cors": {
        "origins": [],
        "allow-credentials": false
      },
      "authentication": {
        "provider": "StaticWebApps"
      }
    }
  },
  "entities": {
    "Asset": {
      "source": "Asset",
      "graphql": {
        "type": {
          "singular": "Asset",
          "plural": "Assets"
        }
      },
      "permissions": [
        {
          "actions": [
            {
              "action": "read"
            }
          ],
          "role": "anonymous"
        }
      ]
    },
    "AssetData": {
      "source": "Asset",
      "permissions": [
        {
          "actions": [
            {
              "action": "read"
            }
          ],
          "role": "anonymous"
        }
      ]
    },
    "AssetShare": {
      "source": "Asset",
      "permissions": [
        {
          "actions": [
            {
              "action": "read"
            }
          ],
          "role": "anonymous"
        }
      ]
    }
  }
}
```

**Comment by dgcaron** [comment] 2023-06-23 07:21
but AssetShare and AssetData aren't marked with the @model directive? i'll give it a go

**Comment by dgcaron** [comment] 2023-06-23 07:28
ok, addding the assetshare and assetdata to the config actually removes the issue. however, i have multiple models in different containers and only this one has this behaviour. it still feels like a bug if you ask me?

**Comment by Mathos1432** [comment] 2023-06-27 19:30
Thank you for reporting the issue. We're investigating and will work on a fix.
@mbhaskar fyi

**Comment by Aniruddh25** [comment] 2023-07-24 19:26
Closing this as this is the intended behavior as per the investigation in the above comment here: https://github.com/Azure/data-api-builder/issues/1538#issuecomment-1630836030

**Closed by Aniruddh25** 2023-07-24 19:26 UTC
Labels: bug, cosmos, graphql, triage
