### ISSUE TITLE
[RFC]: Adding Cli option to enable Application Insights telemtry

### ISSUE THREAD

**Issue by abhishekkumams** [Azure/data-api-builder#1745] opened 2023-09-25 06:01 UTC
Dab engine supports config with the below telemetry options.
```
{
  "runtime": {
    "telemetry": {
      "application-insights": {
        "enabled": true,
        "connection-string": "{YOUR_APP_INSIGHTS_CONN_STRING}"
      }
  }
}
```

Below is the proposed cli command to add application insights telemetry to the config
```
dab add-telemetry --app-insights-enabled true --app-insights-conn-string "connection string"
```

The `add-telemetry` command is used to add telemetry support to a Data API Builder project. This command will modify the runtime config file to add application Insights telemetry and configure the connection string.

Flags/Options
`--app-insights-enabled`: A boolean flag that specifies whether Application Insights telemetry should be enabled. This flag is required and must be set to either true or false.
`--app-insights-conn-string`: A string that specifies the connection string for the Application Insights resource to which telemetry data should be sent. This flag is required whenever `--app-insights-enabled` is set to true and must be set to a valid connection string.

Here's an example usage of the dab add-telemetry command:
```
dab add-telemetry --app-insights-enabled true --app-insights-conn-string "InstrumentationKey=12345678-1234-1234-1234-123456789012,IngestionEndpoint=<<ingestion_url>>"
```

This command will enable Application Insights telemetry and configure the connection string for the specified resource. Note that the connection string should be replaced with the actual connection string for your Application Insights resource.

**Comment by Aniruddh25** [comment] 2023-10-20 23:46
- #1800  is duplicate of this

**Closed** 2024-01-25 09:19 UTC
Labels: cli, rfc
