### ISSUE TITLE
RFC: Ignore extra columns

### ISSUE THREAD

**Issue by JerryNixon** [Azure/data-api-builder#1606] opened 2023-07-24 20:25 UTC
# Summary
Allow additional fields in REST inbound payloads. 

# Motivation
.NET developers serialize and deserialize JSON payloads into classes. Before this enhancement, DAB would require two different Request and Response payloads. The reason for this is that REST payloads to DAB could not include key and read-only fields. To solve this, .NET developers either 1) maintain two sets of POCO/DTO models - which is far from idea - or 2) manipulate the outbound payload dynamically - which is even further from ideal. 

# Old behavior
This demonstrates DAB behavior we want to change.
## SQL Schema:
````SQL
CREATE TABLE Customer
(
    Id INT PRIMARY KEY IDENTITY(1, 1),
    First VARCHAR(50),
    Last VARCHAR(50),
    Name AS CONCAT(First, ' ', 'Last)
)
````
## POST (insert) `{server}/API/customer` 
Request body:
````JSON
{
    "Id": 1,
    "First": "Jerry",
    "Last": "Nixon",
}
````
Response body:
````JSON
{
    "Id": 1,
    "First": "Jerry",
    "Last": "Nixon",
    "Name": "Jerry Nixon",
}
````
## PUT (update) `{server}/API/customer/Id/1` 
Request body:
````JSON
{
    "First": "Jerry",
    "Last": "Smith"
}
````
> Note: If either `Id` or `Name` were included in the Request body, DAB would return an error.

Response body:
````JSON
{
    "Id": 1,
    "First": "Jerry",
    "Last": "Smith",
    "Name": "Jerry Smith",
}
````

# New behavior
This demonstrates DAB behavior we want as a result of this enhancement.
## SQL Schema:
````SQL
CREATE TABLE Customer
(
    Id INT PRIMARY KEY IDENTITY(1, 1),
    First VARCHAR(50),
    Last VARCHAR(50),
    Name AS CONCAT(First, ' ', 'Last)
)
````
## POST (insert) `{server}/API/customer` 
Request body:
````JSON
{
    "Id": 1,
    "First": "Jerry",
    "Last": "Nixon",
}
````
Response body:
````JSON
{
    "Id": 1,
    "First": "Jerry",
    "Last": "Nixon",
    "Name": "Jerry Nixon",
}
````
## PUT (update) `{server}/API/customer/Id/1` 
Request body:
````JSON
{
    "Id": 1,
    "First": "Jerry",
    "Last": "Smith",
    "Name": "Jerry Smith",
}
````
> Note: Both `Id` and `Name` are included in the Request body. As they are primary key and read-only fields, DAB ignores them. No error is returned (please see configuration setting necessary for this behavior below).

Response body:
````JSON
{
    "Id": 1,
    "First": "Jerry",
    "Last": "Smith",
    "Name": "Jerry Smith",
}
````

# Functional Specifications
This enhancement only applies to the REST side of DAB. 

## The basics
1. This behavior is part of the .9 theme to remove adoption friction for enterprise developers. 
1. DAB behavior does not change from current behavior without configuration flag (see below). 

## Desired behavior
1. Any JSON property that does not map to a database field is ignored. (PUT, POST, DELETE)
1. Any JSON property mapping to a read-only primary key is ignored. 
1. Any JSON property referring to a read-only, computed column is ignored.
> Ignoring read-only fields requires knowledge of the database object metadata. 

## Configuration change
Introduce `request-body-strict` to the dab-config.json file. 

````json
{
  "runtime": {
    "rest": {
      "enabled": true,
      "path": "/api",
      "request-body-strict":  false 👈
    },
  }
}
````

|Value|Meaning
|-|-
|true|Extra fields are not allowed, results in error
|false|Extra fields are allowed, ignored

> Note: when the value is not present in the config file, it is the same as being present as `true`; that is, strict mode is on. 

## Normal behavior does not change

 * If a key is read-write and I include it in the request payload, is the DB be updated during a PUT? Yes. 
 * If a key is read-write and I include it in the request payload, is the DB be updated during a POST? Yes. 

## Enhancement Q&A (when configured to `not-strict`)

 * Can properties mapping to read-only keys (db-generated) be included in the Insert payloads? Yes.
 * Can properties mapping to read-only keys (db-generated) be included in the Update payloads? Yes.
 * What happens when properties mapping to read-only keys are included? They are ignored.
 * Can properties mapping to read-only computed fields be included in the Insert payloads? Yes.
 * Can properties mapping to read-only computed fields be included in the Update payloads? Yes.
 * What happens when properties mapping to read-only computed fields are included? They are ignored.
 * Can properties not mapping to any database field be included in the Insert payloads? Yes.
 * Can properties not mapping to any database field be included in the Update payloads? Yes.
 * What happens when properties not mapping to any database field are included? They are ignored.
 * Does property data type change (e.g.: scalar, array, object) this behavior? No. Regular REST limitations apply.
 * How many extra fields are supported? Is there a max? No. Regular REST limitations apply.
 * Are ignored properties forwarded to the response payload? Never. They are ignored.  
 * Are ignored properties populated in the GET response payload? Never. They are ignored.  
 * Are ignored properties compared to the URL key value? Never. They are ignored.  
 * Can I bypass the need for metadata by indicating which fields are read-only somehow? No.

## OpenAPI Updated
OpenAPI will need to be updated to reflect this change in payload requirements. 

# References
Discussion around this originally started here: #1453, #158

**Comment by ayush3797** [comment] 2023-07-25 06:06
When strict mode = false, we will allow extraneous fields in the request body. So to speak, we won't include them in the actual update/insert query that we generate because we cannot mutate a read-only field. As I mentioned, this can be implemented only for pg/mssql right now as for MySql we don't have a solution yet.

**Comment by ayush3797** [comment] 2023-07-25 08:47
A question for PUT/PATCH requests:
In PUT/PATCH requests, the primary keys are allowed to be present only in the request URL. If we are operating with strict mode=false, do we want to allow the primary key fields to be present in the request body as well (and just ignore them)?

**Comment by ayush3797** [comment] 2023-07-25 08:52
Also @JerryNixon, I am a bit confused with the examples PUT(insert) and POST(update) that you have provided. For PUT(insert), I don't see PK being included in the url. Did you intend to include it but maybe missed it? And same confusion for POST(update). First, POST operation being used with UPDATE seems a bit confusing. Also the url contains the value of PK, however POST requests don't allow any PKs in url.

**Comment by JerryNixon** [comment] 2023-07-25 19:57
> When strict mode = false, we will allow extraneous fields in the request body. So to speak, we won't include them in the actual update/insert query that we generate because we cannot mutate a read-only field. As I mentioned, this can be implemented only for pg/mssql right now as for MySql we don't have a solution yet.

Understood. While this is true, should we validate `strict:false` is incompatible with "mysql" in `data-source.database-type`?

````json
"data-source" {
  "database-type": "mysql",
  "connection-string": ""
}
`````

> A question for PUT/PATCH requests @JerryNixon : In PUT/PATCH requests, the primary keys are allowed to be present only in the request URL. If we are operating with strict mode=false, do we want to allow the primary key fields to be present in the request body as well (and just ignore them)?

That's right. Yes. 

> Also @JerryNixon, I am a bit confused with the examples PUT(insert) and POST(update) that you have provided. For PUT(insert), I don't see PK being included in the url. Did you intend to include it but maybe missed it? For POST(update). - First, POST operation being used with phrase UPDATE seems a bit confusing. Also, the url contains the value of PK, however POST requests don't allow any PKs in url.

Yep, I update the original comment to correctly be `post` and `put` respectively.

**Comment by ayush3797** [comment] 2023-07-26 06:55
> Understood. While this is true, should we validate strict:false is incompatible with "mysql" in data-source.database-type?

Makes sense to me

**Comment by ayush3797** [comment] 2023-07-28 20:40
@JerryNixon, what is the expected behavior with autogenerated fields when we operated in non-strict mode? Do we allow the user to provide their value in the request body for POST operation?

**Comment by ayush3797** [comment] 2023-07-28 21:04
By autogenerated fields, I mean fields like `id int IDENTITY(5001, 1) PRIMARY KEY` and not the calculated fields (which are also autogenerated based on other columns). Just wanted to take the ambiguity out of the picture.

**Comment by JerryNixon** [comment] 2023-07-31 18:22
> @JerryNixon, what is the expected behavior with autogenerated fields when we operate in non-strict mode? Do we allow the user to provide their value in the request body for POST/PUT/PATCH operations?

Autogenerated fields are read-only fields.

**Comment by seantleonard** [comment] 2023-08-01 17:54
> Can properties not mapping to any database field be included in the Insert payloads? Yes.
> Can properties not mapping to any database field be included in the Update payloads? Yes.
> What happens when properties not mapping to any database field are included? They are ignored.

1. When `"request-body-strict":  false`, how do we define a bad request where the HTTP 400 response code is returned? 

- One consequence of this is that we would now support developers creating POCO/DTO models with virtually unlimited, arbitrarily named fields. Does having minimal guard rails help reduce possibility of:
    - errors/backwards compatibility, if we ever want to be more restrictive in the future to disallow invalid fields
    - spend unnecessary compute attempting to parse maliciously crafted requests to find a small set of valid fields randomly placed in a large set of invalid fields

2. How are permissions evaluated when calculated, read-only, and/or invalid fields are present in the request payload?
 - Today, DAB doesn't support updating the primary key value of an entity, even if the table column autogenerates a value like `IDENTITY()`
   - Would a PUT/PATCH request whose request body includes read-only and calculated fields be subject to permissions evaluation even if those read-only/calculated field values are not modified as a result of the request?

**Comment by ayush3797** [comment] 2023-08-02 10:37
Hey @JerryNixon, due to the limitations of .NET cli, we cannot have something like rest.request-body-strict as the name of the cli flag that we want to add. Reason being - if a boolean flag is included in the init command, it does not matter what value you assign to the flag, it will always be set as true. If we omit the flag from init command, it will mean rest.request-body-strict=false, which is not the default behavior we want. So basically, you cannot set `rest.request-body-strict` as false using cli. 

What we can do is that we can rename the flag to something like `rest.request-body-flexible` or `request-body-relaxed`. So, when the flag is omitted from the init command, it would mean that the `rest.request-body-flexible`(/`relaxed`) = false, which is what we want as default behavior. 

My only question to you is what name would you prefer? Happy to have any other suggestion that you might have.

**Comment by seantleonard** [comment] 2023-08-02 15:24
> due to the limitations of .NET cli

Specifically, the package `commandlineparser` https://github.com/commandlineparser/commandline

**Comment by seantleonard** [comment] 2023-08-19 00:18
Bumping this @JerryNixon

**Comment by seantleonard** [comment] 2023-09-08 19:10
> > Can properties not mapping to any database field be included in the Insert payloads? Yes.
> > Can properties not mapping to any database field be included in the Update payloads? Yes.
> > What happens when properties not mapping to any database field are included? They are ignored.
> 
> 1. When `"request-body-strict":  false`, how do we define a bad request where the HTTP 400 response code is returned?
> 
> * One consequence of this is that we would now support developers creating POCO/DTO models with virtually unlimited, arbitrarily named fields. Does having minimal guard rails help reduce possibility of:
>   
>   * errors/backwards compatibility, if we ever want to be more restrictive in the future to disallow invalid fields
>   * spend unnecessary compute attempting to parse maliciously crafted requests to find a small set of valid fields randomly placed in a large set of invalid fields
> 
> 2. How are permissions evaluated when calculated, read-only, and/or invalid fields are present in the request payload?
> 
> * Today, DAB doesn't support updating the primary key value of an entity, even if the table column autogenerates a value like `IDENTITY()`
>   
>   * Would a PUT/PATCH request whose request body includes read-only and calculated fields be subject to permissions evaluation even if those read-only/calculated field values are not modified as a result of the request?

@jerrynixon, can you elaborate on how you envision us handling the above? 

One more question too:
- If an 'extraneous' field such as a PK is included in both the URI and REST request body, and `request-body-string`==false, do we care if the values differ? (bad request) or just fully ignore? 
  - If for whatever reason a customer thinks that they are updating a record with id=1 because that is specified in the request body, but the URI denotes `/id/2`, the customer may ask why the 'wrong' record was updated

**Comment by seantleonard** [comment] 2023-09-08 21:29
Ah I see this: "Are ignored properties compared to the URL key value? Never. They are ignored."

**Closed** 2023-09-18 09:37 UTC
Labels: improvement, rfc
