### ISSUE TITLE
[Enhancement]: Add `telemetry` to the CLI

### ISSUE THREAD

**Issue by JerryNixon** [Azure/data-api-builder#1800] opened 2023-10-10 22:00 UTC
### What happened?

We are adding this to the config:

```json
{
  "runtime": {
    //...
    "telemetry": {
      "application-insights": {
        "enabled": true,    // To enable/disable application insights telemetry
        "connection-string": "{APP_INSIGHTS_CONNECTION_STRING}" // Application Insights connection string to send telemetry
      }
    }
    //...
  }
}
```

But we have no way to add/mod it with the CLI.

### Version

Future

### What database are you using?

Azure SQL

### What hosting model are you using?

Local (including CLI)

### Which API approach are you accessing DAB through?

REST, GraphQL

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Aniruddh25** [comment] 2023-10-20 23:47
- Duplicate of #1745

**Closed by Aniruddh25** 2023-10-20 23:47 UTC
Labels: triage
