### ISSUE TITLE
Error when receiving Decimal value without a decimal present 

### ISSUE THREAD

**Issue by jshallBRI** [Azure/data-api-builder#1629] opened 2023-08-11 20:35 UTC
### What happened?

When trying to update a Numeric or Decimal column in an Azure SQL database using GraphQL, the update will work **only if a decimal value is present**.  If an integer is present, e.g. 123, I receive the following error from the server:

"Unable to cast object of type 'HotChocolate.Language.IntValueNode' to type 'HotChocolate.Language.FloatValueNode'."

If I change that updated value to 123.45, the update will go through successfully.  This behavior is consistent across both create and update operations (both with the field being the only one included, or other fields being updated along with it).

[Error.txt](https://github.com/Azure/data-api-builder/files/12324905/Error.txt)
[Success.txt](https://github.com/Azure/data-api-builder/files/12324906/Success.txt)

The problem that I am running into is that I am using the URQL client to access the DAB GraphQL server, and it does not include the decimal portion of the number if it is zero (123.0 is sent as 123, resulting in the error above).

I would expect DAB to accept an integer value for a Decimal field.

### Version

Microsoft.DataApiBuilder 0.7.5+2f938a6dfe4b90c26d9e24352b38280cb6e66f15

### What database are you using?

Azure SQL

### What hosting model are you using?

Static Web Apps (SWA)

### Which API approach are you accessing DAB through?

GraphQL

### Relevant log output

```Text
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST http://localhost:5000/graphql application/json 436
info: Microsoft.AspNetCore.Cors.Infrastructure.CorsService[4]
      CORS policy execution successful.
dbug: Azure.DataApiBuilder.Service.AuthenticationHelpers.ClientRoleHeaderAuthenticationMiddleware[0]       
      657e14e3-16dd-4c65-bbfb-ed63ad19d1de: Request authentication state: Anonymous.
dbug: Azure.DataApiBuilder.Service.AuthenticationHelpers.ClientRoleHeaderAuthenticationMiddleware[0]       
      657e14e3-16dd-4c65-bbfb-ed63ad19d1de: The request will be executed in the context of Anonymous role  
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'Hot Chocolate GraphQL Pipeline'
fail: Azure.DataApiBuilder.Service.Startup[0]
      Unable to cast object of type 'HotChocolate.Language.IntValueNode' to type 'HotChocolate.Language.FloatValueNode'.
fail: Azure.DataApiBuilder.Service.Startup[0]
         at Azure.DataApiBuilder.Service.Services.ResolverMiddleware.ExtractValueFromIValueNode(IValueNode 
value, IInputField argumentSchema, IVariableValueCollection variables)
         at Azure.DataApiBuilder.Service.Resolvers.BaseSqlQueryStructure.GQLMutArgumentToDictParams(IMiddlewareContext context, String fieldName, IDictionary`2 mutationParameters)
         at Azure.DataApiBuilder.Service.Resolvers.SqlUpdateStructure..ctor(IMiddlewareContext context, String entityName, ISqlMetadataProvider sqlMetadataProvider, IAuthorizationResolver authorizationResolver, GQLFilterParser gQLFilterParser, IDictionary`2 mutationParams, HttpContext httpContext)
         at Azure.DataApiBuilder.Service.Resolvers.SqlMutationEngine.PerformMutationOperation(String entityName, Operation operationType, IDictionary`2 parameters, IMiddlewareContext context)
         at Azure.DataApiBuilder.Service.Resolvers.SqlMutationEngine.ExecuteAsync(IMiddlewareContext context, IDictionary`2 parameters)
         at Azure.DataApiBuilder.Service.Services.ResolverMiddleware.InvokeAsync(IMiddlewareContext context)
         at HotChocolate.Utilities.MiddlewareCompiler`1.ExpressionHelper.AwaitTaskHelper(Task task)        
         at HotChocolate.Execution.Processing.Tasks.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)
         at HotChocolate.Execution.Processing.Tasks.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Hot Chocolate GraphQL Pipeline'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 POST http://localhost:5000/graphql application/json 436 - 200 - application/json;+charset=utf-8 1614.2282ms
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by seantleonard** [comment] 2023-08-14 23:25
Thank you for reporting, we will investigate

**Comment by MrMossevig** [comment] 2023-11-13 10:22
Same issue here. The problem is that JS automatically stripes floats with .0, so this bug materializes quite often, especially when using floats with few decimal points.

**Comment by pingu2k4** [comment] 2024-04-16 10:43
Still seeing the same issue in 0.11.127. Kind of stumped as to how to get around this currently and allow integer values to be given where something is stored as a decimal.

**Comment by pingu2k4** [comment] 2024-04-16 11:53
For the time being, I've built a couple extension methods to handle this. Whenever I am assigning a value to a decimal before sending it back to DAB as a create / update operation, I am first passing the value through this small extension method. It will add on a small number if the current value is an integer, and so when DAB gets the value it is in fact a decimal. Then when the database gets it, it stores the correct value by losing the precision required for that small addition.

In the case of the database having a `DECIMAL(18,2)` for example, and calling this with `maxDecimals = 2` (correlating to the SQL type), it would add 0.001 onto any integers, which would then be lost when stored in the database.

```csharp
public static decimal FixDecimalValue(this decimal value, int maxDecimals = 2)
{
    if (value % 1 == 0)
        return value + (1 / (decimal) Math.Pow(10, maxDecimals + 1));
    return value;
}
public static decimal? FixDecimalValue(this decimal? value, int maxDecimals = 2)
{
    if (value is null)
        return null;
    if (value % 1 == 0)
        return value + (1 / (decimal) Math.Pow(10, maxDecimals + 1));
    return value;
}
```

Its not ideal, but so long as its always used to manipulate any values we pass to DAB first, and aligns with our DB types correctly, then it should work. And once the issue is fixed with DAB, its just one place you need to make changes (remove the extension methods) and then fix the compilation issues by removing references to them, and should be all good to go.

**Closed** 2024-05-13 04:46 UTC
Labels: bug, cri
